apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-product
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mkanus/argocd-deploy.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: product
  syncPolicy:
    automated:
      prune: true
      selfHeal: true